"""Implementation-free extension contracts for Gaia application adapters."""

from gaia.spi.auth import AuthenticationError, AuthnProvider
from gaia.spi.cache import CacheProvider
from gaia.spi.context import ContextProvider, ContextQuery, RunSession
from gaia.spi.embedding import EmbeddingFunction, EmbeddingProvider
from gaia.spi.events import EventEnvelope, EventPublisher
from gaia.spi.guardrail import (
    ContentGuardrail,
    GuardrailAction,
    GuardrailContext,
    GuardrailFailureMode,
    GuardrailResult,
    GuardrailStage,
)
from gaia.spi.memory import MemoryItem, MemoryStore
from gaia.spi.model import (
    ModelCallContext,
    ModelMessage,
    ModelProvider,
    ModelResult,
    ModelStreamChunk,
    ModelUsage,
)
from gaia.spi.prompt import (
    PromptArtifact,
    PromptLifecycleStatus,
    PromptMessage,
    PromptProvider,
    PromptRef,
    PromptRegistry,
    PromptRelease,
    PromptValidation,
    PromptVersion,
)
from gaia.spi.rag import (
    Chunker,
    Citation,
    DocumentAccess,
    DocumentChunk,
    DocumentLoader,
    DocumentParser,
    DocumentSource,
    IngestionResult,
    IngestionStatus,
    LoadedDocument,
    ParsedDocument,
    ParsedSection,
    RetrievalHit,
    RetrievalRequest,
    Retriever,
)
from gaia.spi.rate_limit import RateLimitDecision, RateLimiter
from gaia.spi.tool import (
    ReadTool,
    ReconcileHandler,
    ScenarioSideEffect,
    ScenarioTools,
    ToolHandler,
    ToolReference,
    ToolValue,
    WriteAdapter,
)

__all__ = [
    "AuthenticationError",
    "AuthnProvider",
    "CacheProvider",
    "Chunker",
    "Citation",
    "ContentGuardrail",
    "ContextProvider",
    "ContextQuery",
    "DocumentAccess",
    "DocumentChunk",
    "DocumentLoader",
    "DocumentParser",
    "DocumentSource",
    "EmbeddingFunction",
    "EmbeddingProvider",
    "EventEnvelope",
    "EventPublisher",
    "GuardrailAction",
    "GuardrailContext",
    "GuardrailFailureMode",
    "GuardrailResult",
    "GuardrailStage",
    "IngestionResult",
    "IngestionStatus",
    "LoadedDocument",
    "MemoryItem",
    "MemoryStore",
    "ModelCallContext",
    "ModelMessage",
    "ModelProvider",
    "ModelResult",
    "ModelStreamChunk",
    "ModelUsage",
    "ParsedDocument",
    "ParsedSection",
    "PromptArtifact",
    "PromptLifecycleStatus",
    "PromptMessage",
    "PromptProvider",
    "PromptRef",
    "PromptRegistry",
    "PromptRelease",
    "PromptValidation",
    "PromptVersion",
    "RateLimitDecision",
    "RateLimiter",
    "ReadTool",
    "ReconcileHandler",
    "RetrievalHit",
    "RetrievalRequest",
    "Retriever",
    "RunSession",
    "ScenarioSideEffect",
    "ScenarioTools",
    "ToolHandler",
    "ToolReference",
    "ToolValue",
    "WriteAdapter",
]
